#pragma once

#include <driver/gpio.h>
#include <driver/spi_common.h>

#define WEC_FIRMWARE_VERSION "0.1.47"
#define WEC_PRODUCT_URL "https://weclawbot.link"
#define WEC_PRODUCT_HOST "weclawbot.link"

#ifndef CONFIG_WEC_DEVELOPMENT_BUILD
#define CONFIG_WEC_DEVELOPMENT_BUILD 0
#endif

#if CONFIG_WEC_DEVELOPMENT_BUILD
#define WEC_SCREEN_TITLE "微笺（开发版）"
#else
#define WEC_SCREEN_TITLE "微笺屏"
#endif

#define WEC_I2C_HOST I2C_NUM_0
#define WEC_I2C_SDA_PIN GPIO_NUM_13
#define WEC_I2C_SCL_PIN GPIO_NUM_14
#define WEC_SHTC3_I2C_ADDR 0x70

#define WEC_BATTERY_ADC_GPIO GPIO_NUM_4

#define WEC_RLCD_SPI_HOST SPI3_HOST

#define WEC_BOOT_BUTTON_GPIO GPIO_NUM_0
#define WEC_KEY_BUTTON_GPIO GPIO_NUM_18

#define WEC_RLCD_DC_PIN GPIO_NUM_5
#define WEC_RLCD_CS_PIN GPIO_NUM_40
#define WEC_RLCD_SCK_PIN GPIO_NUM_11
#define WEC_RLCD_MOSI_PIN GPIO_NUM_12
#define WEC_RLCD_RST_PIN GPIO_NUM_41
#define WEC_RLCD_TE_PIN GPIO_NUM_6

#define WEC_RLCD_WIDTH 400
#define WEC_RLCD_HEIGHT 300
#define WEC_RLCD_FRAME_BYTES ((WEC_RLCD_WIDTH * WEC_RLCD_HEIGHT) / 8)

#define WEC_CONTENT_BITMAP_X 16
#define WEC_CONTENT_BITMAP_Y 42
#define WEC_CONTENT_BITMAP_WIDTH 368
#define WEC_CONTENT_BITMAP_HEIGHT 206

#define WEC_HTTP_TIMEOUT_MS 30000
#define WEC_QR_POLL_INTERVAL_MS 2000
#define WEC_QR_EXPIRY_MS 180000

#ifndef CONFIG_WEC_SCREENSAVER_RETURN_SEC
#define CONFIG_WEC_SCREENSAVER_RETURN_SEC 20
#endif

#ifndef CONFIG_WEC_AUTO_PAGE_SEC
#define CONFIG_WEC_AUTO_PAGE_SEC 12
#endif

#define WEC_NVS_NAMESPACE "weclaw"
#define WEC_CONFIG_NAMESPACE "config"
#define WEC_NOTES_NAMESPACE "notes"
#define WEC_WECHAT_NAMESPACE "wechat"
